jobs:
  workflow2_job1:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Install CUE
        uses: cue-lang/setup-cue@v0.0.1
        with:
          version: v0.4.1-beta.6
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test
      - name: Run
        run: go run main.go "from workflow 2 using ${{ matrix.go-version }}"
      - name: Regenerate YAML from CUE
        run: cue cmd genworkflows
      - name: Check commit is clean
        run: test -z "$(git status --porcelain)" || (git status; git diff; false)
"on":
  - push
  - pull_request
name: Workflow 2
